### ISSUE TITLE
打开软件报错

### ISSUE THREAD

**Issue by liujvnes** [ylsdamxssjxxdd/eva#1]
![屏幕截图 2024-03-18 144211](https://github.com/ylsdamxssjxxdd/eva/assets/25132014/3e0670a3-88e0-421e-8c93-a17626d70484)

另外能否添加对ollama？

**Comment by ylsdamxssjxxdd** [comment]
我打包的时候可能搞错了，我把组件都给你你再看看，在release的cuda版本修复里

**Comment by ylsdamxssjxxdd** [comment]
现在应该修复了，你下载最新版看看~
机体也可以像ollama那样对外暴露服务，在设置里切换为服务模式~
