### ISSUE TITLE
Can't launch app due to missing .dll file.

### ISSUE THREAD

**Issue by JohnClaw** [ylsdamxssjxxdd/eva#13]
When i start eva, i get this error message:
![image](https://github.com/user-attachments/assets/54eab6be-b522-4d1c-a471-205eab1d2449)
 Where can i download libggml.dll? Help me, please.

**Comment by ylsdamxssjxxdd** [comment]
maybe your computer does not support Vulkan or does not have a graphics card, Can you tell me your computer configuration? And you can try eva-b3600-cpu.exe.

**Comment by JohnClaw** [comment]
I can't run cpu version either. When i try to do that, i get the same error message:
![image](https://github.com/user-attachments/assets/cfeed22c-2824-4df5-8c81-c04fbc8d6bfb)
I hadn't any problems with previous versions of eva. Both builds (cpu and vulkan) worked without errors. My laptop configuration: Ryzen 7 4700u, igpu Vega 7, 16gb ram, Windows 11. Do you know kobold.cpp app? It is like eva: it can run llms on cpu or on Vulkan. It works fine on my laptop. So my hardware is Vulkan compatible.

**Comment by JohnClaw** [comment]
> Maybe your computer does not support Vulkan or does not have a graphics card, Can you tell me your computer configuration? And you can try eva-b3600-cpu.exe.😀

I can't run cpu version either. When i try to do that, i get the same error message:
![image](https://github.com/user-attachments/assets/a61223ee-8cd7-40bf-8826-917258654024)
I hadn't any problems with previous versions of eva. Both builds (cpu and vulkan) worked without errors. My laptop configuration: Ryzen 7 4700u, igpu Vega 7, 16gb ram, Windows 11. Do you know kobold.cpp app (https://github.com/LostRuins/koboldcpp)? It is like eva: it can run llms on cpu or on Vulkan. It works fine on my laptop. So my hardware is Vulkan compatible.

**Comment by ylsdamxssjxxdd** [comment]
I found that the libgomp-1.dll library is missing, and now I have uploaded a new eva, you can download and try again. Thank you for your feedback~

**Comment by JohnClaw** [comment]
> I found that the libgomp-1.dll library is missing, and now I have uploaded a new eva, you can download and try again. Thank you for your feedback~

The problem is fixed. Thank you very much.
